/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import ViewLog.MenuDashboard;
import ViewLog.MenuAnggota;
import java.awt.Color;
/**
 *
 * @author ASUS TUF
 */
public class DashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Dashbord
     */
    int xx, xy;
    public DashboardAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelkiri = new javax.swing.JPanel();
        Libraries = new javax.swing.JLabel();
        PnBook = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        PanelDashboard = new javax.swing.JPanel();
        PanelLine = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ButonDashboard = new javax.swing.JLabel();
        PanelDashboard4 = new javax.swing.JPanel();
        PanelLine8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ButonRiwayat = new javax.swing.JLabel();
        Menu2 = new javax.swing.JLabel();
        PanelDashboard3 = new javax.swing.JPanel();
        PanelLine7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ButonPengembalian = new javax.swing.JLabel();
        PanelDashboard5 = new javax.swing.JPanel();
        PanelLine9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ButonPeminjaman = new javax.swing.JLabel();
        PanelAnggota1 = new javax.swing.JPanel();
        PanelLine2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ButonAnggota = new javax.swing.JLabel();
        PanelBook = new javax.swing.JPanel();
        PanelLine5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ButonBook = new javax.swing.JLabel();
        Panelkanan = new javax.swing.JPanel();
        Panelatas = new javax.swing.JPanel();
        Paneldasar = new javax.swing.JPanel();
        Panelinti = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        Panelkiri.setBackground(new java.awt.Color(255, 255, 255));

        Libraries.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Libraries.setForeground(new java.awt.Color(102, 102, 102));
        Libraries.setText("MyLibraries");

        PnBook.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        PnBook.setForeground(new java.awt.Color(102, 102, 102));
        PnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/stack-of-books (3).png"))); // NOI18N

        Menu.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        Menu.setForeground(new java.awt.Color(102, 102, 102));
        Menu.setText("MENU");

        PanelDashboard.setBackground(new java.awt.Color(255, 255, 255));
        PanelDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelDashboardMouseClicked(evt);
            }
        });

        PanelLine.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelLineLayout = new javax.swing.GroupLayout(PanelLine);
        PanelLine.setLayout(PanelLineLayout);
        PanelLineLayout.setHorizontalGroup(
            PanelLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        PanelLineLayout.setVerticalGroup(
            PanelLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dashboard.png"))); // NOI18N

        ButonDashboard.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        ButonDashboard.setForeground(new java.awt.Color(102, 102, 102));
        ButonDashboard.setText("Dashboard");
        ButonDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButonDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButonDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButonDashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelDashboardLayout = new javax.swing.GroupLayout(PanelDashboard);
        PanelDashboard.setLayout(PanelDashboardLayout);
        PanelDashboardLayout.setHorizontalGroup(
            PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDashboardLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(ButonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDashboardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );
        PanelDashboardLayout.setVerticalGroup(
            PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(ButonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDashboardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        PanelDashboard4.setBackground(new java.awt.Color(255, 255, 255));

        PanelLine8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelLine8Layout = new javax.swing.GroupLayout(PanelLine8);
        PanelLine8.setLayout(PanelLine8Layout);
        PanelLine8Layout.setHorizontalGroup(
            PanelLine8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        PanelLine8Layout.setVerticalGroup(
            PanelLine8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/report.png"))); // NOI18N

        ButonRiwayat.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        ButonRiwayat.setForeground(new java.awt.Color(102, 102, 102));
        ButonRiwayat.setText("Riwaayat");
        ButonRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButonRiwayatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButonRiwayatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButonRiwayatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelDashboard4Layout = new javax.swing.GroupLayout(PanelDashboard4);
        PanelDashboard4.setLayout(PanelDashboard4Layout);
        PanelDashboard4Layout.setHorizontalGroup(
            PanelDashboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDashboard4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(ButonRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(PanelDashboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDashboard4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLine8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );
        PanelDashboard4Layout.setVerticalGroup(
            PanelDashboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDashboard4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDashboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(ButonRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelDashboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDashboard4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLine8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Menu2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        Menu2.setForeground(new java.awt.Color(102, 102, 102));
        Menu2.setText("Laporan");

        PanelDashboard3.setBackground(new java.awt.Color(255, 255, 255));

        PanelLine7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelLine7Layout = new javax.swing.GroupLayout(PanelLine7);
        PanelLine7.setLayout(PanelLine7Layout);
        PanelLine7Layout.setHorizontalGroup(
            PanelLine7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        PanelLine7Layout.setVerticalGroup(
            PanelLine7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/return.png"))); // NOI18N

        ButonPengembalian.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        ButonPengembalian.setForeground(new java.awt.Color(102, 102, 102));
        ButonPengembalian.setText("Pengembalian");
        ButonPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButonPengembalianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButonPengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButonPengembalianMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelDashboard3Layout = new javax.swing.GroupLayout(PanelDashboard3);
        PanelDashboard3.setLayout(PanelDashboard3Layout);
        PanelDashboard3Layout.setHorizontalGroup(
            PanelDashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDashboard3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(ButonPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(PanelDashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDashboard3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLine7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );
        PanelDashboard3Layout.setVerticalGroup(
            PanelDashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDashboard3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(ButonPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelDashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDashboard3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLine7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        PanelDashboard5.setBackground(new java.awt.Color(255, 255, 255));

        PanelLine9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelLine9Layout = new javax.swing.GroupLayout(PanelLine9);
        PanelLine9.setLayout(PanelLine9Layout);
        PanelLine9Layout.setHorizontalGroup(
            PanelLine9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        PanelLine9Layout.setVerticalGroup(
            PanelLine9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/download.png"))); // NOI18N

        ButonPeminjaman.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        ButonPeminjaman.setForeground(new java.awt.Color(102, 102, 102));
        ButonPeminjaman.setText("Peminjaman");
        ButonPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButonPeminjamanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButonPeminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButonPeminjamanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelDashboard5Layout = new javax.swing.GroupLayout(PanelDashboard5);
        PanelDashboard5.setLayout(PanelDashboard5Layout);
        PanelDashboard5Layout.setHorizontalGroup(
            PanelDashboard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDashboard5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(ButonPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(PanelDashboard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDashboard5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLine9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );
        PanelDashboard5Layout.setVerticalGroup(
            PanelDashboard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDashboard5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDashboard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(ButonPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelDashboard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDashboard5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLine9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        PanelAnggota1.setBackground(new java.awt.Color(255, 255, 255));
        PanelAnggota1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelAnggota1MouseClicked(evt);
            }
        });

        PanelLine2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelLine2Layout = new javax.swing.GroupLayout(PanelLine2);
        PanelLine2.setLayout(PanelLine2Layout);
        PanelLine2Layout.setHorizontalGroup(
            PanelLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        PanelLine2Layout.setVerticalGroup(
            PanelLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/people.png"))); // NOI18N

        ButonAnggota.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        ButonAnggota.setForeground(new java.awt.Color(102, 102, 102));
        ButonAnggota.setText("Anggota");
        ButonAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButonAnggotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButonAnggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButonAnggotaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelAnggota1Layout = new javax.swing.GroupLayout(PanelAnggota1);
        PanelAnggota1.setLayout(PanelAnggota1Layout);
        PanelAnggota1Layout.setHorizontalGroup(
            PanelAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAnggota1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(ButonAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(PanelAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelAnggota1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );
        PanelAnggota1Layout.setVerticalGroup(
            PanelAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAnggota1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButonAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelAnggota1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelAnggota1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );

        PanelBook.setBackground(new java.awt.Color(255, 255, 255));

        PanelLine5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelLine5Layout = new javax.swing.GroupLayout(PanelLine5);
        PanelLine5.setLayout(PanelLine5Layout);
        PanelLine5Layout.setHorizontalGroup(
            PanelLine5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        PanelLine5Layout.setVerticalGroup(
            PanelLine5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/open-book (1).png"))); // NOI18N

        ButonBook.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        ButonBook.setForeground(new java.awt.Color(102, 102, 102));
        ButonBook.setText("Book");
        ButonBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButonBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButonBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButonBookMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelBookLayout = new javax.swing.GroupLayout(PanelBook);
        PanelBook.setLayout(PanelBookLayout);
        PanelBookLayout.setHorizontalGroup(
            PanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBookLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(ButonBook, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(PanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelBookLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLine5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );
        PanelBookLayout.setVerticalGroup(
            PanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(ButonBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelBookLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelLine5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout PanelkiriLayout = new javax.swing.GroupLayout(Panelkiri);
        Panelkiri.setLayout(PanelkiriLayout);
        PanelkiriLayout.setHorizontalGroup(
            PanelkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelkiriLayout.createSequentialGroup()
                .addGroup(PanelkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDashboard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelkiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PanelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelkiriLayout.createSequentialGroup()
                                    .addGroup(PanelkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PnBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addComponent(Libraries)
                                    .addGap(2, 2, 2)))
                            .addGroup(PanelkiriLayout.createSequentialGroup()
                                .addGroup(PanelkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelkiriLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(Menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelkiriLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(PanelAnggota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(PanelBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PanelDashboard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PanelDashboard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)))))
                .addGap(163, 163, 163))
        );
        PanelkiriLayout.setVerticalGroup(
            PanelkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelkiriLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PanelkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelkiriLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Libraries)))
                .addGap(18, 18, 18)
                .addComponent(Menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(PanelAnggota1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDashboard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDashboard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(Menu2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDashboard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );

        getContentPane().add(Panelkiri, java.awt.BorderLayout.LINE_START);

        Panelkanan.setBackground(new java.awt.Color(255, 255, 255));
        Panelkanan.setLayout(new java.awt.BorderLayout());

        Panelatas.setBackground(new java.awt.Color(123, 160, 236));
        Panelatas.setForeground(new java.awt.Color(102, 153, 255));
        Panelatas.setPreferredSize(new java.awt.Dimension(1000, 70));

        javax.swing.GroupLayout PanelatasLayout = new javax.swing.GroupLayout(Panelatas);
        Panelatas.setLayout(PanelatasLayout);
        PanelatasLayout.setHorizontalGroup(
            PanelatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1047, Short.MAX_VALUE)
        );
        PanelatasLayout.setVerticalGroup(
            PanelatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Panelkanan.add(Panelatas, java.awt.BorderLayout.PAGE_START);

        Paneldasar.setBackground(new java.awt.Color(255, 255, 255));
        Paneldasar.setPreferredSize(new java.awt.Dimension(1095, 700));

        Panelinti.setBackground(new java.awt.Color(255, 255, 255));
        Panelinti.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout PaneldasarLayout = new javax.swing.GroupLayout(Paneldasar);
        Paneldasar.setLayout(PaneldasarLayout);
        PaneldasarLayout.setHorizontalGroup(
            PaneldasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneldasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Panelinti, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        PaneldasarLayout.setVerticalGroup(
            PaneldasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneldasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Panelinti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        Panelkanan.add(Paneldasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(Panelkanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void ButonPengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonPengembalianMouseExited
        // TODO add your handling code here:
        ButonPengembalian.setBackground(new Color(250, 250, 250)); //untuk mengganti warna ketika mouse di arahkan ke Dashboard
        PanelLine7.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_ButonPengembalianMouseExited

    private void ButonPengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonPengembalianMouseEntered
        // TODO add your handling code here:
        ButonPengembalian.setBackground(new Color(250, 250, 250)); //untuk mengganti warna ketika mouse di arahkan ke Dashboard
        PanelLine7.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_ButonPengembalianMouseEntered

    private void ButonPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonPengembalianMouseClicked
        // TODO add your handling code here:
        ButonPengembalian.setBackground(new Color(250, 250, 250)); //untuk mengganti warna ketika mouse di arahkan ke Dashboard
        PanelLine7.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_ButonPengembalianMouseClicked

    private void ButonRiwayatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonRiwayatMouseExited
        // TODO add your handling code here:
        ButonRiwayat.setBackground(new Color(250, 250, 250)); //untuk mengganti warna ketika mouse di arahkan ke Dashboard
        PanelLine8.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_ButonRiwayatMouseExited

    private void ButonRiwayatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonRiwayatMouseEntered
        // TODO add your handling code here:
        ButonRiwayat.setBackground(new Color(250, 250, 250)); //untuk mengganti warna ketika mouse di arahkan ke Dashboard
        PanelLine8.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_ButonRiwayatMouseEntered

    private void ButonRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonRiwayatMouseClicked
        // TODO add your handling code here:
        ButonRiwayat.setBackground(new Color(250, 250, 250)); //untuk mengganti warna ketika mouse di arahkan ke Dashboard
        PanelLine8.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_ButonRiwayatMouseClicked

    private void ButonBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonBookMouseExited
        // TODO add your handling code here:
        ButonBook.setBackground(new Color(250, 250, 250)); //untuk mengganti warna ketika mouse di arahkan ke Dashboard
        PanelLine5.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_ButonBookMouseExited

    private void ButonBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonBookMouseEntered
        // TODO add your handling code here:
        ButonBook.setBackground(new Color(250, 250, 250)); //untuk mengganti warna ketika mouse di arahkan ke Dashboard
        PanelLine5.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_ButonBookMouseEntered

    private void ButonBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonBookMouseClicked
        // TODO add your handling code here:
        ButonBook.setBackground(new Color(250, 250, 250)); //untuk mengganti warna ketika mouse di arahkan ke Dashboard
        PanelLine5.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_ButonBookMouseClicked

    private void ButonDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonDashboardMouseExited
        // TODO add your handling code here:
        PanelDashboard.setBackground(new Color(255, 255, 255)); //untuk mengganti warna ketika mouse tidak di arahkan ke Dashboard
        PanelLine.setBackground(new Color(255, 255, 255)); //untuk mengganti warna ketika mouse tidak di arahkan ke Dashboard
    }//GEN-LAST:event_ButonDashboardMouseExited

    private void ButonDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonDashboardMouseEntered
        // TODO add your handling code here:
        PanelDashboard.setBackground(new Color(250, 250, 250)); //untuk mengganti warna ketika mouse di arahkan ke Dashboard
        PanelLine.setBackground(new Color(0, 102, 153));//untuk mengganti warna ketika mouse di arahkan ke Dashboard
    }//GEN-LAST:event_ButonDashboardMouseEntered

    private void ButonDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonDashboardMouseClicked
        // TODO add your handling code here:
        PanelDashboard.setBackground(new Color(240, 240, 240)); //Pada source ini kami menambahkan kodingan untuk menampilkan menu dashboard kedalam dashboard yang sudah dibuat
        PanelLine.setBackground(new Color(0, 102, 153));
        Panelinti.removeAll();
        Panelinti.add(new MenuDashboard());
        Panelinti.repaint();
        Panelinti.revalidate();
    }//GEN-LAST:event_ButonDashboardMouseClicked

    private void ButonPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonPeminjamanMouseClicked
        // TODO add your handling code here:
        ButonPeminjaman.setBackground(new Color(240, 240, 240)); //untuk mengganti warna ketika mouse di arahkan ke Dashboard
        PanelLine9.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_ButonPeminjamanMouseClicked

    private void ButonPeminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonPeminjamanMouseEntered
        // TODO add your handling code here:
        ButonPeminjaman.setBackground(new Color(250, 250, 250)); //untuk mengganti warna ketika mouse di arahkan ke Dashboard
        PanelLine9.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_ButonPeminjamanMouseEntered

    private void ButonPeminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonPeminjamanMouseExited
        // TODO add your handling code here:
        ButonPeminjaman.setBackground(new Color(250, 250, 250)); //untuk mengganti warna ketika mouse di arahkan ke Dashboard
        PanelLine9.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_ButonPeminjamanMouseExited

    private void ButonAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonAnggotaMouseClicked
        // TODO add your handling code here:
        ButonAnggota.setBackground(new Color(240, 240, 240)); //Pada source ini kami menambahkan kodingan untuk menampilkan menu dashboard kedalam dashboard yang sudah dibuat
        PanelLine2.setBackground(new Color(0, 102, 153));        
    }//GEN-LAST:event_ButonAnggotaMouseClicked

    private void ButonAnggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonAnggotaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ButonAnggotaMouseEntered

    private void ButonAnggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButonAnggotaMouseExited
        // TODO add your handling code here:
        PanelAnggota1.setBackground(new Color(255, 255, 255)); //untuk mengganti warna ketika mouse tidak di arahkan ke Dashboard
        PanelLine2.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_ButonAnggotaMouseExited

    private void PanelAnggota1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelAnggota1MouseClicked
        // TODO add your handling code here:  
        ButonAnggota.setBackground(new Color(240, 240, 240)); //Pada source ini kami menambahkan kodingan untuk menampilkan menu dashboard kedalam dashboard yang sudah dibuat
        PanelLine2.setBackground(new Color(0, 102, 153));
        
        Panelinti.removeAll();
        Panelinti.add(new MenuAnggota());
        Panelinti.repaint();
        Panelinti.revalidate();
        
        
        
        
    }//GEN-LAST:event_PanelAnggota1MouseClicked

    private void PanelDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelDashboardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButonAnggota;
    private javax.swing.JLabel ButonBook;
    private javax.swing.JLabel ButonDashboard;
    private javax.swing.JLabel ButonPeminjaman;
    private javax.swing.JLabel ButonPengembalian;
    private javax.swing.JLabel ButonRiwayat;
    private javax.swing.JLabel Libraries;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Menu2;
    private javax.swing.JPanel PanelAnggota1;
    private javax.swing.JPanel PanelBook;
    private javax.swing.JPanel PanelDashboard;
    private javax.swing.JPanel PanelDashboard3;
    private javax.swing.JPanel PanelDashboard4;
    private javax.swing.JPanel PanelDashboard5;
    private javax.swing.JPanel PanelLine;
    private javax.swing.JPanel PanelLine2;
    private javax.swing.JPanel PanelLine5;
    private javax.swing.JPanel PanelLine7;
    private javax.swing.JPanel PanelLine8;
    private javax.swing.JPanel PanelLine9;
    private javax.swing.JPanel Panelatas;
    private javax.swing.JPanel Paneldasar;
    private javax.swing.JPanel Panelinti;
    private javax.swing.JPanel Panelkanan;
    private javax.swing.JPanel Panelkiri;
    private javax.swing.JLabel PnBook;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
